"""__

Revision ID: 7b2ec6374006
Revises: ffd176ad67c8
Create Date: 2023-05-13 22:26:17.533939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2ec6374006'
down_revision = 'ffd176ad67c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('clicks', sa.Integer(), nullable=True))
    op.add_column('url', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('url', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'description')
    op.drop_column('url', 'title')
    op.drop_column('url', 'clicks')
    # ### end Alembic commands ###
