"""initial migration

Revision ID: c6dd25a49fa2
Revises: 2c884e0b14cc
Create Date: 2023-05-14 02:31:51.497259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6dd25a49fa2'
down_revision = '2c884e0b14cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
